### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by AggelosM** [mlamp/imdb-rotten-score#2]
> Rotten Tomatoes is no longer issuing API keys at the time of registration. We will be reviewing each application to ensure the usage of our data aligns with our Brand Guidelines and will provision keys if approved. The policy change will allow us to better service our existing developer community and to ensure that new additions are valuable partners that add to the community.

**Comment by mlamp** [comment]
Are you related with Rotten Tomatoes or do you have answer for how would it possible to get key for such project?

**Comment by amaklp** [comment]
Sorry I was copy-pasting. No I'm not related and I think it's pretty much impossible to get a key right now.

**Comment by mlamp** [comment]
Yeah, no worries, gonna discontinue this project, sadly they disabled API key creation for nonofficial projects.
